version: '3'

services:

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/cryptobot
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
